spring.application.name=user-service
server.port=8082
spring.data.mongodb.uri=mongodb://admin:felipediogo@localhost:27017/booking-demo
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-mcdamd0brvi77z7i.us.auth0.com/
spring.security.oauth2.resourceserver.jwt.audience=https://bookingdemo.felipe.io/api/auth/